pipeline:
  sources:
    website:
      urls:
        - https://docs.konghq.com/konnect/network-resiliency/
        - https://docs.konghq.com/konnect/network/
        - https://docs.konghq.com/konnect/gateway-manager/
        - https://docs.konghq.com/konnect/gateway-manager/data-plane-nodes/
        - https://docs.konghq.com/konnect/gateway-manager/data-plane-nodes/secure-communications/
        - https://docs.konghq.com/konnect/org-management/system-accounts/
        - https://docs.konghq.com/konnect/api-products/
        - https://docs.konghq.com/konnect/api-products/service-documentation/
        - https://docs.konghq.com/konnect/api-products/productize-service
      content_class: "page-content"
    pdfs:
      - ~/Documents/KonnectSecurityReliabilityOverview.pdf
text_splitter:
  type: sentence_transformer
  markdown:
    chunk_size: 1000
    chunk_overlap: 200
    separators: []  # Optional custom separators
  recursive_character:
    chunk_size: 1000
    chunk_overlap: 200
    separators: ["\n\n", "\n", " ", "", "###", "##", '#']
  sentence_transformer:
    chunk_size: 1500
    chunk_overlap: 200
    #model_name: "all-MiniLM-L6-v2"
    model_name: "sentence-transformers/all-mpnet-base-v2"
  spacy:
    chunk_size: 1500
    chunk_overlap: 200
    pipeline: "en_core_web_sm"
embeddings:
  type: huggingface  # or "fastembed"
  huggingface:
    model_name: "sentence-transformers/all-mpnet-base-v2"
    # model_name: "BAAI/bge-large-en-v1.5"
    model_kwargs:
      device: "cpu"
    encode_kwargs:
      normalize_embeddings: true
  fastembed:
    model_name: "BAAI/bge-small-en-v1.5"
    max_length: 512
    batch_size: 256
vectorstore:
  type: chroma
  chroma:
    persist_directory: "./chroma_db"
    collection_name: "kong_docs"
content_parser:
  qa:
    patterns:
      - type: "explicit"
        question_pattern: "Q:|Question:"
        answer_pattern: "A:|Answer:"
      - type: "header"
        header_pattern: "##\\s+.+\\?"
scoring:
  type: "hybrid"    # Options: "hybrid", "bm25", "vector"
  parameters:
    k: 4            # Default number of results to return
  hybrid:
    bm25_weight: 0.3
    vector_weight: 0.7
  bm25:
    # BM25 specific parameters if needed
    tokenizer: "simple"  # Optional: could add custom tokenization options
    b: 0.75             # Optional: BM25 parameter for length normalization
    k1: 1.5            # Optional: BM25 parameter for term frequency scaling
  vector:
    # Vector specific parameters if needed
    distance_metric: "cosine"  # Optional: specify distance metric
    min_score: 0.0
